import{a as h,i as n,S as y}from"./assets/vendor-64b55ca9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function L(s,o){const a=document.querySelector(".gallery");o&&(a.innerHTML="");const r=s.map(e=>`
      <div class="photo-card">
        <a href="${e.largeImageURL}" target="_blank">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><i class="img-text">Likes </i><span>${e.likes}</span></p>
          <p><i class="img-text">Views </i><span>${e.views}</span></p>
          <p><i class="img-text">Comments </i><span>${e.comments}</span></p>
          <p><i class="img-text">Downloads </i><span>${e.downloads}</span></p>
        </div>
      </div>
    `).join("");a.innerHTML+=r,m.refresh()}const v="42334631-07f239856d3b6a49db441bfb9";let d=0,u=0;async function f(s,o,a=!0){querySelector(".gallery");const r=document.querySelector(".loader"),e=document.querySelector("#load-more");r.classList.remove("is-hidden"),e.classList.add("is-hidden");try{const t=await h.get(`https://pixabay.com/api/?key=${v}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${o}`);d=t.data.totalHits,u+=t.data.hits.length,console.log(t.data),r.classList.add("is-hidden"),t.data.hits.length===0?u>=d?n.info({title:"Info",message:"We are sorry, but you have reached the end of search results."}):n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(L(t.data.hits,a),m.refresh(),setTimeout(()=>{const g=document.querySelector(".photo-card").getBoundingClientRect().height;window.scrollBy({top:g*2,behavior:"smooth"})},100),e.classList.remove("is-hidden"))}catch(t){console.error("Error fetching images:",t),r.style.display="none",n.error({title:"Error",message:"Failed to fetch images. Please try again later."})}}const m=new y(".gallery a"),b=document.querySelector("#search-form"),p=document.querySelector("#search-input");let l="",c=1;b.addEventListener("submit",s=>{if(l=p.value.trim(),c=1,s.preventDefault(),!l){n.warning({title:"Warning",message:"Please enter a search query"});return}f(l,c,!0),p.value=""});document.querySelector("#load-more").addEventListener("click",()=>{c+=1,f(l,c,!1)});
//# sourceMappingURL=commonHelpers.js.map
